### PR TITLE
Fixed handling of aggregate extent and image size on geotiff write.

### LINKED ISSUE #360: Geotiff Writer does not use the right number of pixels
### Expected situation

When I save a tile from a  `RasterFrameLayer` as `GeoTiff`, I would expect that the size of the pixel would be the same for the output `GeoTiff` than the `RasterFRameLayer`.

### Current situation

When I use a filter condition to keep only a tile from a  `RasterFrameLayer` and I write it as `GeoTiff`, the resulting `GeoTiff` has the number of pixels than the original image instead of the number of pixels of the tile.

### How to reproduce

See: https://gist.github.com/jdenisgiguere/980ca9f28d5ded5da0d30c39fea17e2f based on code provided by @metasim on gitter.im.

### PR DESCRIPTION
**Pull request by metasim**
Closes #360 

Screen Shot 2019-09-22 at 4 23 18 PM
Screen Shot 2019-09-22 at 4 23 47 PM

### CODE REVIEW

File: datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala [hunk 1]
```diff
@@ -67,27 +67,21 @@ class GeoTiffDataSource
...
-      layer.toMultibandRaster(tileCols, cols.toInt, rows.toInt)
-    } else {
-      require(parameters.crs.nonEmpty, "A destination CRS must be provided")
-      TileRasterizerAggregate(df, parameters.crs.get, None, parameters.rasterDimensions)
-    }
+    val destCRS = parameters.crs.orElse(df.asLayerSafely.map(_.crs)).getOrElse(
+      throw new IllegalArgumentException("A destination CRS must be provided")
+    )
+
+    val input = df.asLayerSafely.map(layer =>
```
Comment (vpipkt) [inline datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala]: Perhaps add an overload for `TileRasterizerAggregate.collect` where the type of the first arg is `RasterFrameLayer` that does some of this work? Feels noisy and implementation-y here.

File: datasource/src/test/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSourceSpec.scala [hunk 2]
```diff
@@ -89,6 +91,15 @@ class GeoTiffDataSourceSpec
 
   describe("GeoTiff writing") {
 
+    def checkTiff(file: Path, cols: Int, rows: Int, extent: Extent, cellType: Option[CellType] = None) = {
```
Comment (vpipkt) [inline datasource/src/test/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSourceSpec.scala]: 😸

File: datasource/src/test/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSourceSpec.scala [hunk 3]
```diff
@@ -217,6 +223,42 @@ class GeoTiffDataSourceSpec
...
+
+    it("should produce the correct subregion from layer") {
+      import spark.implicits._
+      val rf = SinglebandGeoTiff(TestData.singlebandCogPath.getPath)
+        .projectedRaster.toLayer(128, 128).withExtent()
+
+      val out = Paths.get("target", "example3-geotiff.tif")
+      logger.info(s"Writing to $out")
+
+      val bitOfLayer = rf.filter($"spatial_key.col" === 0 && $"spatial_key.row" === 0)
```
Comment (vpipkt) [inline datasource/src/test/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSourceSpec.scala]: 👍

File: docs/src/main/paradox/release-notes.md [hunk 4]
```diff
@@ -4,6 +4,7 @@
 
 ### 0.8.2
 
+* Fixed handling of aggregate extent and image size on GeoTIFF writing. ([#362](https://github.com/locationtech/rasterframes/issues/362))
```
Comment (vpipkt) [inline docs/src/main/paradox/release-notes.md]: Some good citizen clean up things to consider:

```suggestion
* Bumped Spark dependency to version 2.3.4. #350 
* Fixed handling of aggregate extent and image size on GeoTIFF writing. ([#362](https://github.com/locationtech/rasterframes/issues/362)) 
```
