### PR TITLE
Fixed eager loading of RasterRef fields.

### LINKED ISSUE #372: Cannot fully delay header read when using RasterRefTile
The point of `RasterRef`s is to delay the call to a `RasterSource` until it's absolutely needed, including the encoding into Catalyst memory. Currently the serialization process asks for the `CRS`, `Extent` and `TileDimensions`, due to how tiles encode refs down at the cells level.

### PR DESCRIPTION
**Pull request by metasim**
Closes #372 .

### CODE REVIEW

File: core/src/main/scala/org/locationtech/rasterframes/ref/DelegatingRasterSource.scala [hunk 1]
```diff
@@ -43,7 +43,7 @@ abstract class DelegatingRasterSource(source: URI, delegateBuilder: () => GTRast
       f(_delRef)
     }
     catch {
-      // On this exeception we attempt to recreate the delegate and read again.
+      // On this Exeception we attempt to recreate the delegate and read again.
```
Comment (vpipkt) [inline core/src/main/scala/org/locationtech/rasterframes/ref/DelegatingRasterSource.scala]: 😈 still mis-spelled `Exception`

Comment (metasim) [reply core/src/main/scala/org/locationtech/rasterframes/ref/DelegatingRasterSource.scala]: 🤦‍♂
